### ISSUE TITLE
As a user I want to *hold* the arrow key to select down.

### ISSUE THREAD

**Issue by kawamurakazushi** [kawamurakazushi/figma-walker#1]
As a user I want to *hold* the arrow key to select down.

Currently it only allow single key press, so if you want to go down far you need to press many times.

**Comment by MarioRicalde** [comment]
I found myself discovering this issue when I was using the plugin. Definitely something I'd like to have.

**Comment by kawamurakazushi** [comment]
@MarioRicalde Just updated the plugin, to arrow this feature.
Please try it out!.

**Comment by MarioRicalde** [comment]
Works great, great job! Thanks!
