### ISSUE TITLE
Shortcut to open plugin?

### ISSUE THREAD

**Issue by 1eadz** [kawamurakazushi/figma-walker#12]
Hello,

Can't find the shortcut to open the plugin ^^
I have to do "right clic > plugins > walke" each time to open?

Thank you for your work!
Cheers

**Comment by kawamurakazushi** [comment]
@1eadz Thanks for opening an issue!
Currently the Figma Plugin API doesn't expose keyboard shortcuts.
I'll implement it as soon as it starts supporting.

FYI, you can `⌘ + /` and search for any plugin you want to run.

**Comment by 1eadz** [comment]
@kawamurakazushi Thank you for the quick anwser.
Unfortunately `⌘ + / `doesn't work on AZERTY keyboard...
I have to create custom shortcut on mac so i hope i can use your plugin to remplace the search etc.

**Comment by williamsheldonws** [comment]
To solve this issue I created a keyboard shortcut in Mac keyboard preferences.
![Screen Shot 2019-09-24 at 10 20 01 am](https://user-images.githubusercontent.com/12469914/65472066-05d80200-deb5-11e9-80eb-2e3d87fa5e66.png)

**Comment by kawamurakazushi** [comment]
@williamsheldonws Thanks!
I think currently this is the Figma way to do it!
