### ISSUE TITLE
Is this repo dead? 

### ISSUE THREAD

**Issue by arndeash** [kawamurakazushi/figma-walker#22]
Is this repo dead? I'd love more feature parity with Sketch Runner Pro. I'd even pay for it, like I've don't with Runner Pro. My main missing features is being able to insert team library components, and a better component insert implementation.

**Comment by kawamurakazushi** [comment]
@arndeash 
Yes, better component insert implementation are most wanted features, but as far as I know figma doesn't support for team library components and finding all components from your artboards.

If they support I would love to implement it though...
