### ISSUE TITLE
How do you launch walker using a keyboard?

### ISSUE THREAD

**Issue by adamruf** [kawamurakazushi/figma-walker#30]
How do you launch it using only a keyboard? I looked through the docs and only found keyboard shortcuts for interacting with walker once it's open.

**Comment by kawamurakazushi** [comment]
@adamruf 
If you are using mac, you can use the set it up on keyboard preference.

https://github.com/kawamurakazushi/figma-walker/issues/12#issuecomment-534335175

**Comment by adamruf** [comment]
Makes sense, thank you!
