### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by ichik** [kawamurakazushi/figma-walker#8]
1. Would be really nice to close the window with the shortcut (Escape is the most conventional one)
2. Shortcut for opening Walker would be also nice, but that can be set up using OS tools
3. Select All (⌘+A) for some reason doesn't work in Walker's input

**Comment by kawamurakazushi** [comment]
@ichik Thanks for opening an issue!

> Would be really nice to close the window with the shortcut (Escape is the most conventional one)

Thanks! I just made a quick fix on this one. Please take a look, and have a try!

> Shortcut for opening Walker would be also nice, but that can be set up using OS tools

Yup, I would love to do this, but the Figma Plugin API doesn't expose this yet :(. 
I'll implement it as soon as it supports shortcuts! 
(Side Note: You can run ⌘+/ and search for any plugin you want to run)

> Select All (⌘+A) for some reason doesn't work in Walker's input

Unfortunately, this is more likely a figma's bug, and really not sure I can fix this issue.

**Comment by whjvenyl** [comment]
> Shortcut for opening Walker would be also nice, but that can be set up using OS tools

For anyone wondering how to do this on a mac:
https://support.apple.com/guide/mac-help/create-keyboard-shortcuts-for-apps-mchlp2271/mac

Use this as selector:
Plugins->Figma Walker

**Comment by kawamurakazushi** [comment]
@whjvenyl thanks!
